---

  - name: Check if bash rc has been configured
    become: yes
    lineinfile:
      name: /root/.bashrc
      line: "alias ls='ls --color=auto'"
      state: present
    check_mode: yes
    register: bash_rc
    failed_when: (conf is changed) or (conf is failed)

  - name: Customize Bash RC
    when: bash_rc == False
    copy:
      dest: /root/.bashrc
      content: |
         export HISTTIMEFORMAT="%d/%m/%y %T "
         export PS1='\u@\h:\W $ '
         alias l='ls -CF'
         alias la='ls -A'
         alias ll='ls -alF'
         alias ls='ls --color=auto'
         source /etc/profile.d/bash_completion.sh
         export PS1="\[\e[31m\][\[\e[m\]\[\e[38;5;172m\]\u\[\e[m\]@\[\e[38;5;153m\]\h\[\e[m\] \[\e[38;5;214m\]\W\[\e[m\]\[\e[31m\]]\[\e[m\]\$ "
    tags: ["proxmox", "bash"] 

  - name: Create Bash Profile
    when: bash_rc == False    
    copy:
      dest: /root/.bash_profile
      content: |
         source /root/.bashrc
