---

  - name: Configure TCP Fast open
    copy:
      dest: /etc/sysctl.d/99-xs-tcp-fastopen.conf
      content: |
         net.ipv4.tcp_fastopen=3
    tags: ["proxmox", "tuning", "skip"]
    
  - name: Enable TCP BBR Congestion Control
    copy:
      dest: /etc/sysctl.d/99-bbr-congestion-control.conf
      content: |
         net.core.default_qdisc=fq
         net.ipv4.tcp_congestion_control=bbr    
    tags: ["proxmox", "tuning", "skip"]

  - name: Enable ipv4 Forwarding in /etc/sysctl.conf
    ansible.builtin.lineinfile:
      dest:  /etc/sysctl.conf
      regexp: '^net\.ipv4\.ip\_forward\=1.*$'
      line: 'net.ipv4.ip_forward=1'
    tags: ["proxmox", "tuning", "skip"]   
    
  - name: Optimize Network
    copy:
      dest: /etc/sysctl.d/99-xs-net.conf
      content: |
         net.core.netdev_max_backlog=65536
         net.core.optmem_max=25165824 
         net.core.rmem_max=25165824 
         net.core.somaxconn=8151
         net.core.wmem_max=16777216 
         net.ipv4.conf.all.accept_redirects = 0
         net.ipv4.conf.all.accept_source_route = 0
         net.ipv4.conf.all.log_martians = 0
         net.ipv4.conf.all.rp_filter = 1
         net.ipv4.conf.all.secure_redirects = 0
         net.ipv4.conf.all.send_redirects = 0
         net.ipv4.conf.default.accept_redirects = 0
         net.ipv4.conf.default.accept_source_route = 0
         net.ipv4.conf.default.log_martians = 0
         net.ipv4.conf.default.rp_filter = 1
         net.ipv4.conf.default.secure_redirects = 0
         net.ipv4.conf.default.send_redirects = 0
         net.ipv4.icmp_echo_ignore_broadcasts = 1
         net.ipv4.icmp_ignore_bogus_error_responses = 1
         net.ipv4.ip_local_port_range=1024 65535
         net.ipv4.tcp_base_mss = 1024
         net.ipv4.tcp_challenge_ack_limit = 999999999
         net.ipv4.tcp_fin_timeout=15
         net.ipv4.tcp_keepalive_intvl=30
         net.ipv4.tcp_keepalive_probes=3
         net.ipv4.tcp_keepalive_time=240
         net.ipv4.tcp_limit_output_bytes=65536
         net.ipv4.tcp_max_syn_backlog=10240
         net.ipv4.tcp_max_tw_buckets = 1440000
         net.ipv4.tcp_mtu_probing = 1
         net.ipv4.tcp_rfc1337=1
         net.ipv4.tcp_rmem=8192 87380 16777216
         net.ipv4.tcp_sack=1
         net.ipv4.tcp_max_tw_buckets = 1440000
         net.ipv4.tcp_slow_start_after_idle=0
         net.ipv4.tcp_syn_retries=3
         net.ipv4.tcp_synack_retries = 2
         net.ipv4.tcp_tw_recycle = 0
         net.ipv4.tcp_tw_reuse = 0
         net.ipv4.tcp_wmem=8192 65536 16777216
         net.netfilter.nf_conntrack_generic_timeout = 60
         net.netfilter.nf_conntrack_helper=0
         net.netfilter.nf_conntrack_max = 524288
         net.netfilter.nf_conntrack_tcp_timeout_established = 28800
         net.unix.max_dgram_qlen = 4096
         net.ipv6.conf.all.disable_ipv6=1
         net.ipv6.conf.default.disable_ipv6=1
         net.ipv6.conf.lo.disable_ipv6=1  
    tags: ["proxmox", "tuning", "skip"]               
