---
     
  - name: vzdump Config
    copy:
      dest: /etc/vzdump.conf
      mode: 0777
      content: |
         #tmpdir: /dev/shm # This will write to ramdisk. Enable if you have enough disk space
         #dumpdir: DIR
         #storage: STORAGE_ID
         #mode: snapshot|suspend|stop
         bwlimit: 0
         ionice: 5
         #lockwait: MINUTES
         #stopwait: MINUTES
         #stdexcludes: BOOLEAN
         #mailto: ADDRESSLIST
         #prune-backups: keep-INTERVAL=N[,...]
         #script: FILENAME
         #exclude-path: PATHLIST
    tags: ["proxmox", "vzdump", "skip"]           
    
